#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `scripts/install-reqs.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail


TMPDIR=$(mktemp -d)
function cleanup {
  rm -rf "${TMPDIR}" || true
}
trap cleanup EXIT

################################################################################
bash scripts/utilities/install-basic.sh
################################################################################
cargo install monolith
################################################################################
# For examples/tests:# See .github/dependencies.yml for the list of dependencies.
sudo apt-get update && sudo apt-get install -y bash findutils grep xxd git xxhash rsync expect jq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ ffmpeg gifsicle
################################################################################
sudo apt update
sudo apt install -y yasm nasm cmake libtool autoconf automake git pkg-config \
  build-essential
################################################################################
cd "${TMPDIR}"
git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git
cd SVT-AV1
mkdir build.cmake
cd build.cmake
cmake ..
make -j$(nproc)
sudo make install
sudo ldconfig /usr/local/lib
################################################################################
cd "${TMPDIR}"
git clone https://aomedia.googlesource.com/aom
cd aom
mkdir build.tmp && cd build.tmp
cmake -G "Unix Makefiles" ../ -DCMAKE_INSTALL_PREFIX=/usr/local
make -j$(nproc)
sudo make install
sudo ldconfig /usr/local/lib
################################################################################
cd "${TMPDIR}"
git clone https://git.ffmpeg.org/ffmpeg.git
cd ffmpeg
./configure --enable-libaom --enable-libsvtav1
make -j$(nproc)
sudo make install
sudo ldconfig /usr/local/lib
################################################################################
